# Generated by Django 5.1.2 on 2024-11-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0004_roomcategory_alter_room_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_threshold', models.PositiveIntegerField(default=10)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('supplies', 'Supplies'), ('equipment', 'Equipment')], default='supplies', max_length=20)),
            ],
        ),
    ]
