# Generated by Django 5.1.2 on 2024-11-28 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('id_proof_document', models.FileField(upload_to='id_proofs/')),
                ('payment_mode', models.CharField(max_length=20)),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_services', models.JSONField(default=list)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms_app.booking')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
