# Generated by Django 5.1.2 on 2024-11-29 04:55

import django.db.models.deletion
import hms_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0010_housekeepingtask_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingtask',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='housekeepingtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='housekeepingtask',
            name='task_type',
            field=models.CharField(choices=[('cleaning', 'Room Cleaning'), ('maintenance', 'Maintenance'), ('laundry', 'Laundry'), ('supplies', 'Restock Supplies')], default='cleaning', max_length=20),
        ),
        migrations.AlterField(
            model_name='housekeepingtask',
            name='assigned_to',
            field=models.ForeignKey(default=hms_app.models.HousekeepingTask.get_default_staff, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
