# Generated by Django 5.1.2 on 2024-11-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0012_supplyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_restocked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='pieces', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning Supplies'), ('amenities', 'Guest Amenities'), ('linens', 'Linens'), ('maintenance', 'Maintenance'), ('office', 'Office Supplies')], max_length=20),
        ),
    ]
