# Generated by Django 5.1.2 on 2024-11-29 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0013_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cleanliness_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='review',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms_app.booking'),
        ),
    ]
