# Generated by Django 5.1.2 on 2024-11-30 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0015_payment_roomservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_app.inventoryitem')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
