# Generated by Django 5.1.2 on 2024-11-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0016_supplyusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning Supplies'), ('amenities', 'Guest Amenities'), ('linens', 'Linens'), ('maintenance', 'Maintenance'), ('office', 'Office Supplies')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_restocked',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='minimum_threshold',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, default='pieces', max_length=20, null=True),
        ),
    ]
