# Generated by Django 5.1.2 on 2024-11-30 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0017_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning Supplies'), ('amenities', 'Guest Amenities'), ('linens', 'Linens'), ('maintenance', 'Maintenance'), ('office', 'Office Supplies')], default='cleaning', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_restocked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='minimum_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='Personal hygiene items', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='pieces', max_length=20),
        ),
    ]
