# Generated by Django 5.1.2 on 2024-12-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0021_booking_advance_payment_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
