# Generated by Django 5.1.2 on 2024-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0022_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='advance_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
