# Generated by Django 5.1.2 on 2024-12-01 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0026_remove_payrollrecord_base_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='base_pay',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('housekeeping', 'Housekeeping'), ('management', 'Management'), ('reception', 'Reception')], default='housekeeping', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='shift_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='shift_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
