# Generated by Django 5.1.2 on 2024-12-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0028_staffprofile_base_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='base_pay',
            new_name='base_salary',
        ),
    ]
