# Generated by Django 5.1.2 on 2024-12-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0029_rename_base_pay_staffprofile_base_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffshift',
            name='staff',
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
        migrations.DeleteModel(
            name='RoomService',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.DeleteModel(
            name='StaffShift',
        ),
    ]
